export const sample_shoes: any[] = [
  {
    id: '1',
    name: 'Nike Dunk Low Retro SE',
    delieryTime: '1-2',
    price: 10000,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/nikeshoe-1.png',
    tags: ['Mens', 'Womens', 'Kids'],
  },
  {
    id: '2',
    name: 'Jordan Deja',
    price: 20000,
    delieryTime: '2-3',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/nikeshoe-2.png',
    tags: ['Duncks', 'Kids'],
  },
  {
    id: '3',
    name: 'Nike Air Max Dn',
    price: 15000,
    delieryTime: '1-1',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/nikeshoe-3.png',
    tags: ['Mens', 'Funky'],
  },
  {
    id: '4',
    name: 'Jordan 1',
    price: 23000,
    delieryTime: '1-2',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/nikeshoe-4.png',
    tags: ['Mens', 'Jordan'],
  },
  {
    id: '5',
    name: 'Nike Air Max SYSTM',
    price: 110000,
    delieryTime: '4-5',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/nikeshoe-5.png',
    tags: ['Duncks', 'Killer'],
  },
  {
    id: '6',
    name: 'Nike Air Max fusion',
    price: 90000,
    delieryTime: '4-5',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/nikeshoe-6.png',
    tags: ['Mens', 'Womens', 'Kids'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'Mens', count: 4 },
  { name: 'Womens', count: 2 },
  { name: 'Kids', count: 3 },
  { name: 'Duncks', count: 2 },
  { name: 'Funky', count: 1 },
  { name: 'Jordan', count: 1 },
  { name: 'Killer', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'Jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];
